### ISSUE TITLE
pooled samples

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#34]
pooled samples can be handled in the current model with the addition of a field for the `parent` sample. all samples that went into the one sample would be labeled  with the same ID.

**Comment by DougManuel** [comment]
I agree.

**Comment by NielsNicolai** [comment]
Would a pooled sample not also require to be linked to multiple sites? Currently the ERD does not allow for this.

**Comment by DougManuel** [comment]
ERD has been updated for multiple sites. ERD will be updated soon. 

The relationship be between child and parent samples would benefit from a diagram. I will create a new issue.

**Comment by NielsNicolai** [comment]
In case that you have a pooled sample and you did an analysis on both the parent (which will always be the case) and some/all of its children, you are currently able to link the two sample records in your table by cross-referencing from the parent to the child and vice versa. 

There are however two standing issues that I see:
- In those cases where you do not analyze the children of a pooled sample (because the number of infections is low according to the parent sample), you might still want to indicate that this is a pooled sample to keep track of this information. Currently, there is no such variable (boolean).
- When working with pooled samples you need to link them to multiple Sites. A quick solution to this problem would be to include multiple siteID's (separated by a semicolon) in the sample table. However, I feel that this is not the perfect solution.

**Comment by DougManuel** [comment]
For the first bullet point, I thought we have this ability. The parent sample would childID <> null.

**parent sample**
```
sampleID = 1
parentID = null
childID = 2, 3, 4, 5
```
**child sample of parent**
```
sampleID = 2
parentID = 1
childID = null
```

**Comment by DougManuel** [comment]
For bullet #2. It may not be ideal, but the approach would be to examine the `siteID`s for the children of the parent sample. We could have a reserved entry for the `siteID` for the parent sample, since the parent sample does not have a unique siteID, maybe `siteID` = NA_parent 

I the above example:

**parent sample**
```
siteID = NA_parent
sampleID = 1
parentID = null
childID = 2, 3, 4, 5
```

**first child sample of parent**

```
siteID = WWTP_1
sampleID = 2
parentID = 1
childID = null
```

**the second child sample of the parent**

```
siteID = WWTP_2
sampleID = 3
parentID = 1
childID = null
```

**Comment by vipileggi** [comment]
@DougManuel @NielsNicolai @hswerdfe I'm currently planning on removing the 'parent' 'child' 'pooled' variables for Ontario Template, to reduce complexity and I think this this can readily managed through some backend work using other variables.

**Comment by NielsNicolai** [comment]
> For the first bullet point, I thought we have this ability. The parent sample would childID <> null.
> 
> **parent sample**
> 
> ```
> sampleID = 1
> parentID = null
> childID = 2, 3, 4, 5
> ```
> 
> **child sample of parent**
> 
> ```
> sampleID = 2
> parentID = 1
> childID = null
> ```

@DougManuel I agree that this is the correct approach. However, we should take into account that not all children might be put in the database as sometimes they will not be analyzed individually. In such a case you will not have sampleID's of the children to reference to. Yet, you will still want to indicate that the parent is a pooled sample. This is why I already added the boolean variable `pooled`. Do you agree?

**Comment by NielsNicolai** [comment]
> For bullet #2. It may not be ideal, but the approach would be to examine the `siteID`s for the children of the parent sample. We could have a reserved entry for the `siteID` for the parent sample, since the parent sample does not have a unique siteID, maybe `siteID` = NA_parent
> 
> I the above example:
> 
> **parent sample**
> 
> ```
> siteID = NA_parent
> sampleID = 1
> parentID = null
> childID = 2, 3, 4, 5
> ```
> 
> **first child sample of parent**
> 
> ```
> siteID = WWTP_1
> sampleID = 2
> parentID = 1
> childID = null
> ```
> 
> **the second child sample of the parent**
> 
> ```
> siteID = WWTP_2
> sampleID = 3
> parentID = 1
> childID = null
> ```

This is a good approach, but you might have the same problem as in bullet one, i.e. where the individual children are not in the database as such. In that case, you need to link the different SiteID's to the parent. That's why I suggested allowing for multiple entries in `SiteID`.

**Comment by DougManuel** [comment]
Yes. I agree that it is helpful to have `pooled` variable. 

@NielsNicolai I don't see `pooled` in the model. Did you put it in previously and it was deleted? Do you want to put back in?

**Comment by DougManuel** [comment]
Re: `pooled`. Just to be clear. The entry for all pooled samples would be `siteID` = null, `pooled` = TRUE, `parentID` = null, `childID` <> null. This is a fair amount of repetition....

**For the above parent example**
```
siteID = null
sampleID = 1
parentID = null
childID = 2, 3, 4, 5
pooled = TRUE
```

**Comment by DougManuel** [comment]
> 
> This is a good approach, but you might have the same problem as in bullet one, i.e. where the individual children are not in the database as such. In that case, you need to link the different SiteID's to the parent. That's why I suggested allowing for multiple entries in `SiteID`.

I don't follow how you would have multiple `siteID` in the parent sample. Sorry for being dense. 
`childID` would contain the list. right?
`siteID = null for all pooled samples. Not possible to have a `siteID` for a pooled sample.

Or were you thinking `siteID` would BE the list of children. In which case, what would be use `childID` for?
