### ISSUE TITLE
Site and Sample type

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#61]
I noticed that the options for `Site.type` (where the sample was taken) and `Sample.type` (what kind of sample is taken) are rather limited in the current version. Also, both fields are currently very dependant on each other.

### Site.type
Following an internal discussion, I would suggest to break down `Site.type` based on how far the site is removed from the source. As also proposed in this [report ](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/940919/S0908_Wastewater_C19_monitoring_SAGE.pdf) that was recently published as by the UK governement. 

**1. Near-source**
- airplane
- correctionalFacility
- elementrarySchool
- hospital
- longTermCareFacility
- sewageTruck
- universityCampus
- other

**2. Major sewer pipeline**

**3. Intermediate sewer infrastructure**
- pumpingStation
- holdTank
- retentionPond
- other

**4. Wastewater treatment plant**
- sanitaryMunicipal
- combinedMunicipal
- industrial
- lagoon
- other

**5. Environment**
- river
- lake
- estuary
- sea
- ocean
- other

### Sample.type
A more complete classification for the `Sample.type` could look somewhat like this
- sewerSediment
- rawWastewater
- wwPostGrit
- primarySludge
- primaryEffluent
- secondarySludge
- secondaryEffluent
- water
- faeces
- other

**Comment by vipileggi** [comment]
@NielsNicolai  thanks for posting this issue and link to the UK report. Reading this post and report with interest. Just a quick observation that some of the extended options (e.g., secondary sludge) are not recommended and others on the extended list may not be very common at this time and may be captured under 'other' from a economy of list length perspective. Still I think this issue is important and I've just started reading the report 👍 
FYI I work with the Ontario Ministry of the Environment and Climate Change and I'm a wastewater engineer on a technical working group advising the surveillance initiative group currently being initiated/administered and supported by MECP.

**Comment by NielsNicolai** [comment]
Hi @vipileggi, thanks for your comment! 
I understand that we should not give our users a list with too many options as this might create confusion/frustration. But from a developers point of view, there is no "cost" associated to adding an additional option, so why not..
FYI, I,m a postdoctoral researcher at Université Laval (Québec) with main expertise in modelling, control and automation of water treatment processes.

**Comment by vipileggi** [comment]
@NielsNicolai sure agreed but would be cautious about providing sampling locations that may not yield representative results. Thanks!

**Comment by DougManuel** [comment]
Looks good. Let's implement.

**Comment by NielsNicolai** [comment]
Updated according to the proposal with this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/c797139cb002f789cd38906a7ceeb789a203cd40).

Note that a single level list is used to provide the options. To implement a 2-level list in the Excel templates, use the following [tutorial](https://www.extendoffice.com/documents/excel/5852-excel-multiple-level-drop-down-list.html).
