### ISSUE TITLE
Environmental sampling conditions

### ISSUE THREAD

**Issue by jaizkibel2** [Big-Life-Lab/covid-19-wastewater#73]
Maybe someone with more expertise in wastewater can weight in.

Precipitation: I think this is important especially for combined systems. Some ways to include this, in the Sample table, could be:

1.  Two Boolean variables: 
- precipitationYesterday: Rain or snow on the day before to sampling date..
- precipitationToday. Rain or snow on sampling date.

2.  A Boolean and an int:
- dryWeather: Dry weather conditions on sampling period
- lastWetWeather: Days since last wet weather event.

3. A Boolean and a float: this is probably the best but most involved as it needs units.
- PWWF: Peak Wet Weather Flow during sampling period.
- volumePWWF: volume of a PWWF event in megaliters per day.

Temperature of the influent: a seasonal factor very likely to affect viral measurements. I didn't see it. I saw there is a place to report parameters of the wastewater in Measurements, but I wonder if this is important and could be in the Sample table. 
Another thing to add would be the time from collection to refrigeration. But also autosamplers can be refrigerated. That could be added as well.

Less important:
- Air temperature: I dont think this is needed now.

**Comment by NielsNicolai** [comment]
Hi Karol,

I agree that this is important information for combined sewer systems. That is why the [latest version of the data model ](https://github.com/Big-Life-Lab/covid-19-wastewater/blob/dev/metadata.md)does include an option to log environmental (e.g. precipitation, temperature) and other WWTP variables (flow rates, ww temperature) for later analysis. Both individual measurements or aggregates are possible, using the aggregation field. These measurements are stored as part of the `WWMeasure` table which relates to site specific measurements, not performed on the SARS-CoV-2 sample. And since they are timestamped, there is no need to work with 'day before' or 'days since'.

Does that make any sense?

Niels

**Comment by DougManuel** [comment]
@NielsNicolai and @jaizkibel2 Can we close this issue, or move to V1.0.1?
