### ISSUE TITLE
Meaning of covN1N2avg

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#80]
In the WWMeasure table under the variable 'type', the following option exists
`covN1N2avg`: SARS-CoV-2 gene region average of N1 and N2

Is this one measurement that gives you an average of the quantity of N1 and N2 genes? Or is this an average of 2 measurements?

In the latter case, this should not be on this list. The variable `aggregation` would account for that.

**Comment by DougManuel** [comment]
I agree that this variable should be taken off the type and can be reported as a derived measure.

Note that we are currently allowing user defined "type". Should we make derived variables only allowable under `other` 

Should we have a new category for `derived` and also include a new variable `typeDerived` where a user would indicate the derived variable name? @NielsNicolai

**Comment by vipileggi** [comment]
@NielsNicolai the link of the protocol used by  [J. Peccia](https://docs.google.com/document/d/1tZKcF3-Efvu4rVR3RQloGY2usAHyjWZ9U-EUtOn3lOQ/edit) shows that they average N1 and N2 and report it as an average in GC/mL of sludge (they sample primary sludge).  Also, I prefer having derived measure under other rather than adding new variables. I'm thinking of ways to keep the wide format Excel template within a manageable width :)

**Comment by vipileggi** [comment]
Oops! forgot to copy you Doug @DougManuel on previous comment https://github.com/Big-Life-Lab/covid-19-wastewater/issues/80#issuecomment-767854860

**Comment by DougManuel** [comment]
Let's move this issue to a later version.

Having a variable for derived measures shouldn't increase the width of the wide table, but there are a number of implementation issues that require discussion. 

I lean towards creating a new look-up table `DerivedMeasure` that can describe the calculation of derived measures. This could be a user contributed list. I will describe later.

**Comment by NielsNicolai** [comment]
This option has been removed from the `type` variable in `WWMeasure`.
