### ISSUE TITLE
How are *Default fields used in the Templates by Users

### ISSUE THREAD

**Issue by vipileggi** [Big-Life-Lab/covid-19-wastewater#89]
@DougManuel @NielsNicolai  @hswerdfe sorry I may have raised this before but still not clear on this. What is the best way to populate/use the *Default fields from a Template user perspective? Specifically I currently have 'siteIDDefault' and 'labIDDefault' in the Ontario Template of the Reporter worksheet. Are these values simply the same as siteID and labID, respectively. If so do we need these new variable names? if this approach is important from a relational DB perspective I'm ok with keeping them as they are in the OT.

**Comment by DougManuel** [comment]
There are a few different ways the defaults can be implemented in Excel. 

Here is a somewhat simpler example for using `SiteFractionAnalysedDefault`. The column in WWMeasure for `fractionAlalyzed` (your column `WWmeasure!k`) would contain the formula:

`=IF(ISBLANK(I$2),"", Site!K2)`. Where,
- `I$2` is the `reportDate` column and the function is placed in all rows for that column (drag down for I$2 to I$1000 or so). 
- `Site!K2` is the value for `SiteFractionAnalysedDefault`. 

This would enter the default value from `SiteFractionAnalysedDefault` when `reportDate` has an entry. Provide instruction for people to first enter the reportDate (or another column) and the defaults could be populated.

The is a simple implementation. There are more robust implementations.

Implementation for your example is a bit trickier because there is no `reporterID` in the `Sample` table, where the `SiteID` is completed.

**Comment by DougManuel** [comment]
The development of the defaults wasn't specifically developed for Excel. There may be approached to implement in Excel template that are easier or make more sense, such as making a 'configuration' tab where the defaults are entered and then used in the approach above to pre-populate columns whose values don't change often.

**Comment by vipileggi** [comment]
@DougManuel thanks for the example; clearly see the possible uses. Seems that of the possible immediate solutions (1-3) I prefer the least effort ones (either 2 or 3) for now and work towards the better approach for next version. What do you recommend?

1. include reporterID in Sample table and then create a 'configuration' tab; but this would break the ODMv1.0 (?)
2. change 'nameDefault' to 'names' without Default extension 
3. remove these columns from the OT

**Comment by DougManuel** [comment]
There are a few issues to ponder +/- get advice from advance Excel user about how to best proceed. Suggest:
1) We ask users what they need to help them.
2) There are a few meetings this week with folks interested in developing templates. Let's discuss together with those folks.

**Comment by vipileggi** [comment]
Sounds good and can I close this comment and perhaps reopen similar issue later?

**Comment by DougManuel** [comment]
See also #100.
